-- Recipes surface tables (mirrored in pkm and pkm_test).
-- Safe to re-run.

BEGIN;

DO $$
DECLARE
  schema_name text;
  table_fqn text;
  seq_fqn text;
BEGIN
  FOREACH schema_name IN ARRAY ARRAY['pkm', 'pkm_test']
  LOOP
    table_fqn := format('%I.recipes', schema_name);

    EXECUTE format($sql$
      CREATE TABLE IF NOT EXISTS %s (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        public_id text GENERATED ALWAYS AS ('R' || id::text) STORED UNIQUE,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        title text NOT NULL,
        title_normalized text NOT NULL,
        servings int NOT NULL,
        ingredients text[] NOT NULL,
        instructions text[] NOT NULL,
        notes text,
        search_text text NOT NULL,
        status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'needs_review', 'archived')),
        metadata jsonb,
        source text,
        cuisine text,
        protein text,
        prep_time_minutes int,
        cook_time_minutes int,
        total_time_minutes int GENERATED ALWAYS AS (coalesce(prep_time_minutes, 0) + coalesce(cook_time_minutes, 0)) STORED,
        difficulty text,
        tags text[],
        url_canonical text,
        capture_text text NOT NULL,
        overnight boolean NOT NULL DEFAULT false,
        CONSTRAINT recipes_title_normalized_uidx UNIQUE (title_normalized)
      )
    $sql$, table_fqn);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %s (status, updated_at DESC)',
      schema_name || '_recipes_status_updated_at_idx',
      table_fqn
    );

    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON %s USING GIN (to_tsvector(''simple'', search_text))',
      schema_name || '_recipes_search_text_fts_idx',
      table_fqn
    );

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %s USING GIN (ingredients)',
      schema_name || '_recipes_ingredients_gin_idx',
      table_fqn
    );

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %s USING GIN (tags)',
      schema_name || '_recipes_tags_gin_idx',
      table_fqn
    );

    seq_fqn := format('%I.recipes_id_seq', schema_name);

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pkm_ingest') THEN
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %s TO pkm_ingest', table_fqn);
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO pkm_ingest', seq_fqn);
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pkm_read') THEN
      EXECUTE format('GRANT SELECT ON TABLE %s TO pkm_read', table_fqn);
    END IF;
  END LOOP;
END$$;

COMMIT;
