-- Todoist planning surface tables (prod schema only).
-- Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS pkm.todoist_task_current (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  todoist_task_id text NOT NULL UNIQUE,
  todoist_project_id text,
  todoist_project_name text NOT NULL,
  todoist_section_id text,
  todoist_section_name text,
  raw_title text NOT NULL,
  raw_description text,
  todoist_priority int NOT NULL DEFAULT 1 CHECK (todoist_priority BETWEEN 1 AND 4),
  todoist_due_date date,
  todoist_due_string text,
  todoist_due_is_recurring boolean NOT NULL DEFAULT false,
  project_key text NOT NULL CHECK (project_key IN ('home', 'personal', 'work', 'inbox')),
  lifecycle_status text NOT NULL CHECK (lifecycle_status IN ('open', 'waiting', 'closed')),
  normalized_title_en text NOT NULL,
  task_shape text NOT NULL CHECK (task_shape IN ('project', 'next_action', 'micro_task', 'follow_up', 'vague_note', 'unknown')),
  suggested_next_action text,
  parse_confidence real NOT NULL DEFAULT 0 CHECK (parse_confidence >= 0 AND parse_confidence <= 1),
  review_status text NOT NULL CHECK (review_status IN ('needs_review', 'no_review_needed', 'accepted', 'overridden')),
  review_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  todoist_added_at timestamptz,
  first_seen_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  waiting_since_at timestamptz,
  closed_at timestamptz,
  parsed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pkm.todoist_task_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES pkm.todoist_task_current(id) ON DELETE CASCADE,
  event_at timestamptz NOT NULL DEFAULT now(),
  event_type text NOT NULL,
  changed_fields text[] NOT NULL DEFAULT '{}'::text[],
  before_json jsonb,
  after_json jsonb,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS todoist_task_current_lifecycle_review_idx
  ON pkm.todoist_task_current (lifecycle_status, review_status, project_key, todoist_due_date);

CREATE INDEX IF NOT EXISTS todoist_task_current_review_queue_idx
  ON pkm.todoist_task_current (review_status, parse_confidence, project_key, lifecycle_status, COALESCE(todoist_added_at, first_seen_at), id);

CREATE INDEX IF NOT EXISTS todoist_task_current_waiting_idx
  ON pkm.todoist_task_current (waiting_since_at, todoist_priority DESC)
  WHERE lifecycle_status = 'waiting';

CREATE INDEX IF NOT EXISTS todoist_task_current_updated_at_idx
  ON pkm.todoist_task_current (updated_at DESC);

CREATE INDEX IF NOT EXISTS todoist_task_events_task_event_at_idx
  ON pkm.todoist_task_events (task_id, event_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS todoist_task_events_event_type_idx
  ON pkm.todoist_task_events (event_type, event_at DESC);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pkm_ingest') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pkm.todoist_task_current TO pkm_ingest;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pkm.todoist_task_events TO pkm_ingest;
    GRANT USAGE, SELECT ON SEQUENCE pkm.todoist_task_current_id_seq TO pkm_ingest;
    GRANT USAGE, SELECT ON SEQUENCE pkm.todoist_task_events_id_seq TO pkm_ingest;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pkm_read') THEN
    GRANT SELECT ON TABLE pkm.todoist_task_current TO pkm_read;
    GRANT SELECT ON TABLE pkm.todoist_task_events TO pkm_read;
  END IF;
END$$;

COMMIT;
