-- Active topic state surface (mirrored in pkm and pkm_test).
-- Safe to re-run.

BEGIN;

DO $$
DECLARE
  schema_name text;
  topics_table text;
  state_table text;
  questions_table text;
  actions_table text;
  related_entries_table text;
BEGIN
  FOREACH schema_name IN ARRAY ARRAY['pkm', 'pkm_test']
  LOOP
    topics_table := format('%I.active_topics', schema_name);
    state_table := format('%I.active_topic_state', schema_name);
    questions_table := format('%I.active_topic_open_questions', schema_name);
    actions_table := format('%I.active_topic_action_items', schema_name);
    related_entries_table := format('%I.active_topic_related_entries', schema_name);

    EXECUTE format($sql$
      CREATE TABLE IF NOT EXISTS %s (
        topic_key text PRIMARY KEY,
        title text NOT NULL,
        is_active boolean NOT NULL DEFAULT true,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CHECK (topic_key = lower(topic_key))
      )
    $sql$, topics_table);

    EXECUTE format($sql$
      CREATE TABLE IF NOT EXISTS %s (
        topic_key text PRIMARY KEY REFERENCES %s(topic_key) ON DELETE CASCADE,
        title text NOT NULL DEFAULT '',
        why_active_now text NOT NULL DEFAULT '',
        current_mental_model text NOT NULL DEFAULT '',
        tensions_uncertainties text NOT NULL DEFAULT '',
        state_version int NOT NULL DEFAULT 1 CHECK (state_version >= 1),
        last_session_id text,
        migration_source_entry_id bigint,
        migration_source_content_hash text,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    $sql$, state_table, topics_table);

    EXECUTE format($sql$
      CREATE TABLE IF NOT EXISTS %s (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        topic_key text NOT NULL REFERENCES %s(topic_key) ON DELETE CASCADE,
        question_key text NOT NULL,
        question_text text NOT NULL,
        status text NOT NULL CHECK (status IN ('open', 'closed')),
        sort_order int NOT NULL DEFAULT 0,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        UNIQUE (topic_key, question_key)
      )
    $sql$, questions_table, topics_table);

    EXECUTE format($sql$
      CREATE TABLE IF NOT EXISTS %s (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        topic_key text NOT NULL REFERENCES %s(topic_key) ON DELETE CASCADE,
        action_key text NOT NULL,
        action_text text NOT NULL,
        status text NOT NULL CHECK (status IN ('open', 'done')),
        sort_order int NOT NULL DEFAULT 0,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        UNIQUE (topic_key, action_key)
      )
    $sql$, actions_table, topics_table);

    EXECUTE format($sql$
      CREATE TABLE IF NOT EXISTS %s (
        topic_key text NOT NULL REFERENCES %s(topic_key) ON DELETE CASCADE,
        entry_id bigint NOT NULL,
        relation_type text NOT NULL DEFAULT 'related',
        metadata jsonb,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        PRIMARY KEY (topic_key, entry_id),
        CHECK (btrim(relation_type) <> '')
      )
    $sql$, related_entries_table, topics_table);

    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON %s (updated_at DESC)',
      schema_name || '_active_topic_state_updated_at_idx',
      state_table
    );

    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON %s (topic_key, status, sort_order, id)',
      schema_name || '_active_topic_open_questions_status_idx',
      questions_table
    );

    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON %s (topic_key, status, sort_order, id)',
      schema_name || '_active_topic_action_items_status_idx',
      actions_table
    );

    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON %s (entry_id, topic_key)',
      schema_name || '_active_topic_related_entries_entry_idx',
      related_entries_table
    );

    EXECUTE format($sql$
      INSERT INTO %s (topic_key, title, is_active, created_at, updated_at)
      VALUES
        ('communication', 'communication', true, now(), now()),
        ('parenting', 'parenting', true, now(), now()),
        ('product', 'product', true, now(), now()),
        ('ai', 'ai', true, now(), now())
      ON CONFLICT (topic_key) DO UPDATE
      SET title = EXCLUDED.title,
          is_active = true,
          updated_at = now()
    $sql$, topics_table);

    EXECUTE format($sql$
      INSERT INTO %s (
        topic_key,
        title,
        why_active_now,
        current_mental_model,
        tensions_uncertainties,
        state_version,
        created_at,
        updated_at
      )
      SELECT
        t.topic_key,
        COALESCE(t.title, t.topic_key),
        ''::text,
        ''::text,
        ''::text,
        1,
        now(),
        now()
      FROM %s t
      WHERE t.topic_key IN ('communication', 'parenting', 'product', 'ai')
      ON CONFLICT (topic_key) DO NOTHING
    $sql$, state_table, topics_table);

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pkm_ingest') THEN
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %s TO pkm_ingest', topics_table);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %s TO pkm_ingest', state_table);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %s TO pkm_ingest', questions_table);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %s TO pkm_ingest', actions_table);
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %s TO pkm_ingest', related_entries_table);
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I.active_topic_open_questions_id_seq TO pkm_ingest', schema_name);
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I.active_topic_action_items_id_seq TO pkm_ingest', schema_name);
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pkm_read') THEN
      EXECUTE format('GRANT SELECT ON TABLE %s TO pkm_read', topics_table);
      EXECUTE format('GRANT SELECT ON TABLE %s TO pkm_read', state_table);
      EXECUTE format('GRANT SELECT ON TABLE %s TO pkm_read', questions_table);
      EXECUTE format('GRANT SELECT ON TABLE %s TO pkm_read', actions_table);
      EXECUTE format('GRANT SELECT ON TABLE %s TO pkm_read', related_entries_table);
    END IF;
  END LOOP;
END$$;

COMMIT;
