#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import argparse
import json
import sys


ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = ROOT / "docs/backend_route_registry.json"
OUTPUT_PATH = ROOT / "docs/backend_test_surface_matrix.md"
OPERATOR_CALLERS = {"operators", "debug UI", "PKM UI", "probes"}


def load_registry() -> list[dict]:
    return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))


def as_yes_no(value: bool) -> str:
    return "yes" if value else "no"


def has_contract_tests(tests: list[str]) -> bool:
    return any("api-contract" in test_path for test_path in tests)


def has_integration_tests(tests: list[str]) -> bool:
    return any(".integration." in test_path or "/integration/" in test_path for test_path in tests)


def is_operator_surface(callers: list[str]) -> bool:
    return any(caller in OPERATOR_CALLERS for caller in callers)


def summarize_tests(tests: list[str]) -> str:
    return ", ".join(tests) if tests else "-"


def render(registry: list[dict]) -> str:
    total_routes = len(registry)
    contract_routes = sum(1 for item in registry if has_contract_tests(list(item.get("tests", []))))
    smoke_routes = sum(1 for item in registry if bool((item.get("smoke") or {}).get("enabled")))
    integration_routes = sum(1 for item in registry if has_integration_tests(list(item.get("tests", []))))
    operator_routes = sum(1 for item in registry if is_operator_surface(list(item.get("primary_callers", []))))
    untested_routes = sum(1 for item in registry if not list(item.get("tests", [])))

    lines: list[str] = [
        "# Backend Test Surface Matrix",
        "",
        "Generated from `docs/backend_route_registry.json` by `scripts/CI/generate_backend_test_surface_matrix.py`. Do not edit this file manually.",
        "",
        "## Purpose",
        "- show declared backend route coverage from the route registry",
        "- help agents spot missing contract, smoke, and integration layers quickly",
        "- keep route, doc, and test planning tied to one source of truth",
        "",
        "## Summary",
        f"- total routes: {total_routes}",
        f"- routes with contract tests: {contract_routes}",
        f"- routes with smoke coverage: {smoke_routes}",
        f"- routes with integration tests: {integration_routes}",
        f"- operator/UI/probe routes: {operator_routes}",
        f"- routes with no declared tests: {untested_routes}",
        "",
        "## Matrix",
        "",
        "| Route | Auth | Primary callers | Doc | Contract | Smoke | Integration | Operator/UI/Probe | Tests |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    for item in registry:
        method = item["method"]
        path = item["path"]
        auth = item.get("auth", "-")
        callers = ", ".join(item.get("primary_callers", [])) or "-"
        doc = item["doc"]
        tests = list(item.get("tests", []))
        smoke_enabled = bool((item.get("smoke") or {}).get("enabled"))
        lines.append(
            "| "
            + " | ".join([
                f"`{method} {path}`",
                f"`{auth}`",
                callers,
                f"`{doc}`",
                as_yes_no(has_contract_tests(tests)),
                as_yes_no(smoke_enabled),
                as_yes_no(has_integration_tests(tests)),
                as_yes_no(is_operator_surface(list(item.get('primary_callers', [])))),
                summarize_tests(tests),
            ])
            + " |"
        )

    lines.extend([
        "",
        "## Usage Note",
        "- treat this matrix as a planning and review index, not as proof of behavioral depth; test quality still depends on what each listed file asserts",
        "- if a route changes caller ownership, docs, or tests, update `docs/backend_route_registry.json` first and regenerate this file",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is out of date")
    parser.add_argument("--write", action="store_true", help="write the generated file")
    args = parser.parse_args()

    rendered = render(load_registry())

    if args.write:
        OUTPUT_PATH.write_text(rendered, encoding="utf-8")
        print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
        return 0

    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
        if existing == rendered:
            print("Backend test surface matrix OK")
            return 0
        print("Backend test surface matrix is out of date. Run scripts/CI/generate_backend_test_surface_matrix.py --write")
        return 1

    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
