'use strict';

const path = require('path');
const { Pool } = require(require.resolve('pg', {
  paths: [path.join(__dirname, '../../src/server')],
}));

const RUN_INTEGRATION = String(process.env.PKM_RUN_DB_INTEGRATION || '').trim() === '1';
const INTEGRATION_DB_URL = String(process.env.PKM_DB_INTEGRATION_URL || '').trim();
const describeIntegration = RUN_INTEGRATION ? describe : describe.skip;

function parseConnectionString(connectionString) {
  const url = new URL(connectionString);
  const database = url.pathname.replace(/^\/+/, '');
  if (!database) {
    throw new Error('PKM_DB_INTEGRATION_URL must include a database name');
  }
  return {
    user: decodeURIComponent(url.username || ''),
    password: decodeURIComponent(url.password || ''),
    host: url.hostname,
    port: url.port || '5432',
    database,
    ssl: ['require', 'verify-ca', 'verify-full'].includes(String(url.searchParams.get('sslmode') || '').toLowerCase()),
  };
}

function applyRuntimeDbEnv(connectionString) {
  const parsed = parseConnectionString(connectionString);
  process.env.PKM_INGEST_USER = parsed.user;
  process.env.PKM_INGEST_PASSWORD = parsed.password;
  process.env.PKM_DB_HOST = parsed.host;
  process.env.PKM_DB_PORT = parsed.port;
  process.env.PKM_DB_NAME = parsed.database;
  process.env.PKM_DB_SSL = parsed.ssl ? '1' : '0';
  process.env.PKM_DB_SSL_REJECT_UNAUTHORIZED = '0';
  process.env.PKM_DB_SCHEMA = 'pkm';
}

async function resetIntegrationSchemas(pool) {
  await pool.query('DROP SCHEMA IF EXISTS pkm_test CASCADE');
  await pool.query('DROP SCHEMA IF EXISTS pkm CASCADE');
  await pool.query('CREATE SCHEMA pkm');
  await pool.query('CREATE SCHEMA pkm_test');

  const entriesTableSql = (schema) => `
CREATE TABLE ${schema}.entries (
  id uuid PRIMARY KEY DEFAULT (
    regexp_replace(
      md5(random()::text || clock_timestamp()::text),
      '(.{8})(.{4})(.{4})(.{4})(.{12})',
      E'\\\\1-\\\\2-\\\\3-\\\\4-\\\\5'
    )
  )::uuid,
  entry_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL,
  intent text NOT NULL DEFAULT 'archive',
  capture_text text NOT NULL,
  url text,
  url_canonical text,
  extracted_text text,
  clean_text text,
  content_hash text,
  external_ref jsonb,
  metadata jsonb,
  content_type text,
  title text,
  author text,
  topic_primary text,
  topic_primary_confidence real,
  topic_secondary text,
  topic_secondary_confidence real,
  keywords text[],
  enrichment_status text,
  enrichment_model text,
  prompt_version text,
  gist text,
  retrieval_excerpt text,
  clean_word_count int,
  clean_char_count int,
  extracted_char_count int,
  link_count int,
  link_ratio real,
  boilerplate_heavy boolean,
  low_signal boolean,
  quality_score real,
  idempotency_policy_key text,
  idempotency_key_primary text,
  idempotency_key_secondary text,
  distill_summary text,
  distill_excerpt text,
  distill_version text,
  distill_created_from_hash text,
  distill_why_it_matters text,
  distill_stance text,
  distill_status text,
  distill_metadata jsonb
);
`.trim();

  await pool.query(entriesTableSql('pkm'));
  await pool.query(entriesTableSql('pkm_test'));

  const recipesTableSql = (schema) => `
CREATE TABLE ${schema}.recipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id text GENERATED ALWAYS AS ('R' || id::text) STORED UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  title text NOT NULL,
  title_normalized text NOT NULL UNIQUE,
  servings int NOT NULL,
  ingredients text[] NOT NULL,
  instructions text[] NOT NULL,
  notes text,
  search_text text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  metadata jsonb,
  source text,
  cuisine text,
  protein text,
  prep_time_minutes int,
  cook_time_minutes int,
  total_time_minutes int GENERATED ALWAYS AS (coalesce(prep_time_minutes, 0) + coalesce(cook_time_minutes, 0)) STORED,
  difficulty text,
  tags text[],
  url_canonical text,
  capture_text text NOT NULL,
  overnight boolean NOT NULL DEFAULT false
);
`.trim();

  await pool.query(recipesTableSql('pkm'));
  await pool.query(recipesTableSql('pkm_test'));
  await pool.query(`
CREATE TABLE pkm.recipe_links (
  recipe_id_a bigint NOT NULL REFERENCES pkm.recipes(id) ON DELETE CASCADE,
  recipe_id_b bigint NOT NULL REFERENCES pkm.recipes(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (recipe_id_a, recipe_id_b),
  CONSTRAINT pkm_recipe_links_order_chk CHECK (recipe_id_a < recipe_id_b)
);
`.trim());
  await pool.query(`
CREATE TABLE pkm_test.recipe_links (
  recipe_id_a bigint NOT NULL REFERENCES pkm_test.recipes(id) ON DELETE CASCADE,
  recipe_id_b bigint NOT NULL REFERENCES pkm_test.recipes(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (recipe_id_a, recipe_id_b),
  CONSTRAINT pkm_test_recipe_links_order_chk CHECK (recipe_id_a < recipe_id_b)
);
`.trim());
  await pool.query(`
CREATE TABLE pkm.runtime_config (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
`.trim());
  await pool.query(`
INSERT INTO pkm.runtime_config (key, value, updated_at)
VALUES ('is_test_mode', 'false'::jsonb, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
`.trim());
}

async function setTestMode(pool, enabled) {
  await pool.query(
    `UPDATE pkm.runtime_config
     SET value = $2::jsonb, updated_at = now()
     WHERE key = $1`,
    ['is_test_mode', JSON.stringify(!!enabled)]
  );
}

async function queryOne(pool, sql, params = []) {
  const res = await pool.query(sql, params);
  return res.rows && res.rows[0] ? res.rows[0] : null;
}

describeIntegration('Postgres-backed DB store integration', () => {
  let adminPool = null;
  let envBackup;

  beforeAll(async () => {
    if (!INTEGRATION_DB_URL) {
      throw new Error('PKM_DB_INTEGRATION_URL is required when PKM_RUN_DB_INTEGRATION=1');
    }
    envBackup = { ...process.env };
    applyRuntimeDbEnv(INTEGRATION_DB_URL);
    adminPool = new Pool({ connectionString: INTEGRATION_DB_URL });
    await adminPool.query('SELECT 1');
  });

  beforeEach(async () => {
    jest.resetModules();
    await resetIntegrationSchemas(adminPool);
  });

  afterEach(async () => {
    jest.resetModules();
    try {
      const { closePool } = require('../../src/server/db-pool.js');
      await closePool();
    } catch (_err) {
      // Some tests may not have loaded the app pool.
    }
  });

  afterAll(async () => {
    try {
      const { closePool } = require('../../src/server/db-pool.js');
      await closePool();
    } catch (_err) {
      // no-op
    }
    if (adminPool) {
      await adminPool.end();
    }
    if (envBackup) {
      process.env = envBackup;
    }
  });

  test('write-store insert and update honor active test mode routing', async () => {
    await setTestMode(adminPool, true);
    const { insert, update } = require('../../src/server/db/write-store.js');

    const inserted = await insert({
      input: {
        source: 'webpage',
        capture_text: 'integration body',
        clean_text: 'integration body',
        title: 'Integration draft',
        content_hash: 'hash-write-test',
      },
    });

    expect(inserted.rowCount).toBe(1);
    expect(inserted.rows[0].action).toBe('inserted');

    const prodCount = await queryOne(adminPool, 'SELECT COUNT(*)::int AS count FROM pkm.entries');
    const testRow = await queryOne(
      adminPool,
      'SELECT entry_id, title, clean_text FROM pkm_test.entries WHERE content_hash = $1',
      ['hash-write-test']
    );

    expect(prodCount.count).toBe(0);
    expect(testRow).toEqual(expect.objectContaining({
      title: 'Integration draft',
      clean_text: 'integration body',
    }));

    await update({
      where: { entry_id: testRow.entry_id },
      title: 'Integration updated',
      clean_text: 'integration body updated',
    });

    const updatedRow = await queryOne(
      adminPool,
      'SELECT title, clean_text FROM pkm_test.entries WHERE entry_id = $1',
      [testRow.entry_id]
    );
    expect(updatedRow).toEqual({
      title: 'Integration updated',
      clean_text: 'integration body updated',
    });
  });

  test('read-store readPull follows the active schema selected by runtime test mode', async () => {
    await adminPool.query(
      `INSERT INTO pkm.entries (entry_id, source, intent, capture_text, clean_text, title, content_hash)
       VALUES (101, 'webpage', 'archive', 'prod body', 'prod body', 'Prod copy', 'hash-prod-101')`
    );
    await adminPool.query(
      `INSERT INTO pkm_test.entries (entry_id, source, intent, capture_text, clean_text, title, content_hash)
       VALUES (101, 'webpage', 'archive', 'test body', 'test body', 'Test copy', 'hash-test-101')`
    );

    const { readPull } = require('../../src/server/db/read-store.js');

    await setTestMode(adminPool, false);
    const prodResult = await readPull({ entry_id: 101, shortN: 40, longN: 80 });
    expect(prodResult.rows[0]).toEqual(expect.objectContaining({
      found: true,
      title: 'Prod copy',
      clean_text: 'prod body',
    }));

    await setTestMode(adminPool, true);
    const testResult = await readPull({ entry_id: 101, shortN: 40, longN: 80 });
    expect(testResult.rows[0]).toEqual(expect.objectContaining({
      found: true,
      title: 'Test copy',
      clean_text: 'test body',
    }));
  });

  test('distill-store prod-pinned sync updates production entries even when test mode is enabled', async () => {
    await adminPool.query(
      `INSERT INTO pkm.entries (
         entry_id, source, intent, capture_text, clean_text, title, content_hash, clean_word_count, distill_status
       )
       VALUES (202, 'webpage', 'archive', 'prod source', 'prod source', 'Prod distill target', 'hash-prod-202', 2, 'pending')`
    );
    await adminPool.query(
      `INSERT INTO pkm_test.entries (
         entry_id, source, intent, capture_text, clean_text, title, content_hash, clean_word_count, distill_status
       )
       VALUES (202, 'webpage', 'archive', 'test source', 'test source', 'Test distill target', 'hash-test-202', 2, 'pending')`
    );

    await setTestMode(adminPool, true);
    const {
      getTier2SyncEntryByEntryId,
      persistTier2SyncSuccess,
    } = require('../../src/server/db/distill-store.js');

    const syncTarget = await getTier2SyncEntryByEntryId(202);
    expect(syncTarget).toEqual(expect.objectContaining({
      title: 'Prod distill target',
      content_hash: 'hash-prod-202',
    }));

    const updated = await persistTier2SyncSuccess(202, {
      distill_summary: 'Production summary',
      distill_excerpt: 'Production excerpt',
      distill_version: 'distill_v1',
      distill_created_from_hash: 'hash-prod-202',
      distill_why_it_matters: 'Because production copy should change',
      distill_stance: 'neutral',
      distill_metadata: { source: 'integration-test' },
    });

    expect(updated.rowCount).toBe(1);

    const prodRow = await queryOne(
      adminPool,
      'SELECT distill_summary, distill_status, distill_created_from_hash FROM pkm.entries WHERE entry_id = 202'
    );
    const testRow = await queryOne(
      adminPool,
      'SELECT distill_summary, distill_status, distill_created_from_hash FROM pkm_test.entries WHERE entry_id = 202'
    );

    expect(prodRow).toEqual({
      distill_summary: 'Production summary',
      distill_status: 'completed',
      distill_created_from_hash: 'hash-prod-202',
    });
    expect(testRow).toEqual({
      distill_summary: null,
      distill_status: 'pending',
      distill_created_from_hash: null,
    });
  });

  test('recipes-store create and get follow active test mode schema routing', async () => {
    const { createRecipe, getRecipeByPublicId } = require('../../src/server/db/recipes-store.js');

    await setTestMode(adminPool, true);
    const createdTest = await createRecipe({
      title: 'Lemon Pasta',
      title_normalized: 'lemon pasta',
      servings: 4,
      ingredients: ['pasta', 'lemon'],
      instructions: ['boil', 'mix'],
      notes: null,
      source: 'telegram',
      cuisine: null,
      protein: null,
      prep_time_minutes: 15,
      cook_time_minutes: 20,
      difficulty: null,
      tags: ['weeknight'],
      url_canonical: null,
      capture_text: '# Lemon Pasta',
      overnight: false,
      metadata: null,
      parser_meta: null,
      requested_status: null,
      search_text: 'Lemon Pasta pasta lemon boil mix',
    });

    expect(createdTest.public_id).toBe('R1');

    const prodCountAfterTestWrite = await queryOne(adminPool, 'SELECT COUNT(*)::int AS count FROM pkm.recipes');
    const testCountAfterTestWrite = await queryOne(adminPool, 'SELECT COUNT(*)::int AS count FROM pkm_test.recipes');
    expect(prodCountAfterTestWrite.count).toBe(0);
    expect(testCountAfterTestWrite.count).toBe(1);

    const loadedTest = await getRecipeByPublicId('R1', { includeArchived: true });
    expect(loadedTest).toEqual(expect.objectContaining({
      public_id: 'R1',
      title: 'Lemon Pasta',
    }));

    await setTestMode(adminPool, false);
    const createdProd = await createRecipe({
      title: 'Tomato Soup',
      title_normalized: 'tomato soup',
      servings: 2,
      ingredients: ['tomato'],
      instructions: ['blend'],
      notes: null,
      source: 'telegram',
      cuisine: 'italian',
      protein: null,
      prep_time_minutes: 5,
      cook_time_minutes: 20,
      difficulty: 'easy',
      tags: ['soup'],
      url_canonical: null,
      capture_text: '# Tomato Soup',
      overnight: false,
      metadata: null,
      parser_meta: null,
      requested_status: null,
      search_text: 'Tomato Soup tomato blend',
    });

    expect(createdProd.public_id).toBe('R1');

    const prodCountAfterProdWrite = await queryOne(adminPool, 'SELECT COUNT(*)::int AS count FROM pkm.recipes');
    const testCountAfterProdWrite = await queryOne(adminPool, 'SELECT COUNT(*)::int AS count FROM pkm_test.recipes');
    expect(prodCountAfterProdWrite.count).toBe(1);
    expect(testCountAfterProdWrite.count).toBe(1);
  });

  test('recipes-store search honors alternatives_count up to supported limit', async () => {
    const { createRecipe, searchRecipes } = require('../../src/server/db/recipes-store.js');
    await setTestMode(adminPool, false);

    const basePayload = {
      servings: 2,
      ingredients: ['lemon', 'pasta'],
      instructions: ['mix'],
      notes: null,
      source: 'telegram',
      cuisine: 'italian',
      protein: 'none',
      prep_time_minutes: 5,
      cook_time_minutes: 10,
      difficulty: 'easy',
      tags: ['weeknight'],
      url_canonical: null,
      overnight: false,
      metadata: null,
      parser_meta: null,
      requested_status: null,
    };

    for (let i = 1; i <= 6; i += 1) {
      const title = `Lemon Pasta Variant ${i}`;
      await createRecipe({
        ...basePayload,
        title,
        title_normalized: title.toLowerCase(),
        capture_text: `# ${title}`,
        search_text: `${title} lemon pasta`,
      });
    }

    const result = await searchRecipes({ q: 'lemon pasta', alternatives_count: 4 });

    expect(result.top_hit).toBeTruthy();
    expect(result.alternatives).toHaveLength(4);
    expect(result.total_candidates).toBe(5);
  });

  test('recipes-store link and append note update bidirectional links and note tail', async () => {
    const {
      createRecipe,
      getRecipeByPublicId,
      linkRecipes,
      appendRecipeNote,
    } = require('../../src/server/db/recipes-store.js');
    await setTestMode(adminPool, false);

    const payloadBase = {
      servings: 2,
      ingredients: ['tomato', 'beef'],
      instructions: ['cook'],
      source: 'telegram',
      cuisine: 'italian',
      protein: 'beef',
      prep_time_minutes: 10,
      cook_time_minutes: 25,
      difficulty: 'medium',
      tags: ['dinner'],
      url_canonical: null,
      overnight: false,
      metadata: null,
      parser_meta: null,
      requested_status: null,
    };

    await createRecipe({
      ...payloadBase,
      title: 'Ragu Bolognese',
      title_normalized: 'ragu bolognese',
      notes: 'Family favorite',
      capture_text: '# Ragu Bolognese',
      search_text: 'Ragu Bolognese tomato beef cook',
    });
    await createRecipe({
      ...payloadBase,
      title: 'Pico de Gallo',
      title_normalized: 'pico de gallo',
      notes: null,
      capture_text: '# Pico de Gallo',
      search_text: 'Pico de Gallo tomato',
    });

    const linked = await linkRecipes('R1', 'R2');
    expect(linked.public_id).toBe('R1');
    expect(linked.linked_recipes).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ public_id: 'R2', title: 'Pico de Gallo' }),
      ])
    );

    const linkedBack = await getRecipeByPublicId('R2', { includeArchived: true });
    expect(linkedBack.linked_recipes).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ public_id: 'R1', title: 'Ragu Bolognese' }),
      ])
    );

    await linkRecipes('R2', 'R1');
    const linksCount = await queryOne(adminPool, 'SELECT COUNT(*)::int AS count FROM pkm.recipe_links');
    expect(linksCount.count).toBe(1);

    const updated = await appendRecipeNote('R1', 'This is a very important note.');
    expect(updated.notes).toBe('Family favorite\nThis is a very important note.');
  });
});
